/**
 * Regenerates src/core/shorthands.ts from Chrome's CSSOM: for every
 * property Chrome knows, `style.setProperty(p, "initial")` and read back
 * the longhands it set. Vendor-prefixed names are left out: a prefixed
 * declaration before its standard one is a fallback, not an override.
 *
 *   bun run gen:shorthands
 */
import { resolve } from "node:path";
import { $ } from "bun";
import { View } from "../src/browser/view";

const out = resolve(import.meta.dir, "../src/core/shorthands.ts");

// Runs in the page.
const PAGE = `(() => {
  const el = document.createElement("div");
  const names = new Set();
  for (const key in el.style) {
    if (typeof el.style[key] !== "string" || key === "cssText" || key === "cssFloat") continue;
    const name = key.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());
    if (!/^(webkit|moz|ms|epub)-/.test(name)) names.add(name);
  }
  const table = {};
  for (const name of [...names].sort()) {
    el.removeAttribute("style");
    el.style.setProperty(name, "initial");
    const longhands = Array.from(el.style);
    if (longhands.length > 0 && !(longhands.length === 1 && longhands[0] === name))
      table[name] = longhands;
  }
  return { table, version: navigator.userAgent.match(/Chrome\\/([\\d.]+)/)?.[1] };
})()`;

const view = new View({ engine: "chrome" });
try {
  await view.navigate("about:blank");
  const { table, version } = await view.evaluate<{
    table: Record<string, string[]>;
    version: string;
  }>(PAGE);
  await Bun.write(
    out,
    `// Generated by scripts/gen-shorthands.ts from Chrome ${version}'s CSSOM. Don't edit.

/** Shorthand (or legacy alias) -> the longhands it sets, in Chrome's order. */
export const SHORTHANDS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(table)};
`,
  );
  await $`${resolve(import.meta.dir, "../node_modules/.bin/biome")} format --write ${out}`.quiet();
  console.log(
    `✓ ${Object.keys(table).length} shorthands from Chrome ${version}`,
  );
} finally {
  Bun.WebView.closeAll();
}
